#!/bin/sh

mkdir saved_libs
sudo mv /usr/lib/libiodbc.2.1.18.dylib saved_libs
sudo mv /usr/lib/libiodbcinst.a saved_libs
sudo mv /usr/lib/libiodbc.a saved_libs
sudo mv /usr/lib/libiodbcinst.2.1.18.dylib saved_libs

sudo ln -i -s $(pwd)/db/lib/libiodbc.2.dylib /usr/lib/libiodbc.2.1.18.dylib
sudo ln -i -s $(pwd)/db/lib/libiodbcinst.a /usr/lib/
sudo ln -i -s $(pwd)/db/lib/libiodbc.a /usr/lib/
sudo ln -i -s $(pwd)/db/lib/libiodbcinst.2.dylib /usr/lib/libiodbcinst.2.1.18.dylib

#symlinks
#libiodbc.2.dylib
#libiodbcinst.2.dylib
#libiodbc.dylib
#libiodbcinst.dylib
#libodbc.a

